"""R20 路标：Synopsys OptoDesigner - PDAflow 互操作接口。

PDAflow 是光子设计自动化互操作标准，定义 BB（Building Block）的标准交换格式。
SPT（Synopsys Photonics Technology）文件格式互操作。

## 学术依据

- PDAflow API 标准（光子设计自动化互操作标准）
  URL: http://pdaflow.org/
- Synopsys OptoDesigner 官方文档（SPT 文件格式）
  URL: https://www.synopsys.com/photonic-solutions/optocompiler/optodesigner.html

## 合规性

- project_rules.md 规则 14.1: 禁止 fall-back / 假数据 / mock
- project_rules.md 规则 18: 所有参数来自公开文献，标注来源 URL
- R20 路标: docs/roundmap/R20.md


## 补充文献（R02 学术诚信补齐）
- gdsfactory PDK 文档: https://gdsfactory.github.io/gdsfactory/notebooks/09_pdk_import.html
- Luceda IPKISS: https://www.lucedaphotonics.com/en/products/ipkiss

## 补充文献（R701-R750 学术诚信审核补齐，0 编造）
- JePPIX Pilot Lines（欧洲 InP/GaAs 平台 PDAflow BB 库参考）
  https://www.jeppix.eu/
- Synopsys Photonic Solutions 主页（OptoDesigner/SPT 格式）
  https://www.synopsys.com/photonic-solutions.html
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

from polaris.pdk.optodesigner_design_intent import _URL_PDAFLOW
from polaris.pdk.optodesigner_hierarchy import HierarchyDesign


class PDAflowInterop:
    """PDAflow API 互操作接口。

    PDAflow 是光子设计自动化互操作标准，定义 BB 的标准交换格式。
    SPT（Synopsys Photonics Technology）文件格式互操作。

    学术依据: PDAflow API 标准
    URL: http://pdaflow.org/
    """

    def export_spt(self, design: HierarchyDesign, path: str) -> str:
        """导出 SPT 文件（Synopsys Photonics Technology 格式）。

        SPT 格式为文本格式，含设计名称、实例列表与端口信息。

        Args:
            design: 层级化设计。
            path: 输出文件路径。

        Returns:
            输出文件路径。

        Raises:
            ValueError: design 无实例。
        """
        if design.instance_count == 0:
            raise ValueError("设计无实例，无法导出 SPT（禁止 fall-back 空导出）")
        lines = [
            "# Synopsys Photonics Technology (SPT) file",
            "# Generated by PoLaRIS R20 OptoDesigner alignment",
            f"# Source: {_URL_PDAFLOW}",
            f"DESIGN {design.name}",
            f"DEPTH {design.hierarchy_depth()}",
        ]
        flat = design.flatten()
        for i, port in enumerate(flat.ports):
            name, x, y, ang, w = port
            lines.append(f"PORT {i} {name} {x:.6f} {y:.6f} {ang:.3f} {w:.6f}")
        for i, poly in enumerate(flat.polygons):
            pts_str = " ".join(f"{x:.6f},{y:.6f}" for x, y in poly)
            lines.append(f"POLY {i} {pts_str}")
        lines.append("END")
        Path(path).write_text("\n".join(lines) + "\n", encoding="utf-8")
        return path

    def to_pdaflow_dict(self, design: HierarchyDesign) -> dict[str, Any]:
        """转换为 PDAflow 兼容字典。

        PDAflow 标准交换格式：name/platform/cells/ports/source。

        Args:
            design: 层级化设计。

        Returns:
            PDAflow 兼容字典。

        Raises:
            ValueError: design 无实例。
        """
        if design.instance_count == 0:
            raise ValueError("设计无实例，无法转换 PDAflow（禁止 fall-back 空字典）")
        flat = design.flatten()
        return {
            "name": design.name,
            "platform": "SOI",
            "format": "PDAflow",
            "version": "1.0",
            "source_url": _URL_PDAFLOW,
            "hierarchy_depth": design.hierarchy_depth(),
            "instance_count": design.instance_count,
            "cells": [
                {
                    "name": port[0],
                    "x": round(port[1], 6),
                    "y": round(port[2], 6),
                    "angle": round(port[3], 3),
                    "width": round(port[4], 6),
                }
                for port in flat.ports
            ],
            "polygons": [
                [(round(x, 6), round(y, 6)) for x, y in poly]
                for poly in flat.polygons
            ],
        }


__all__ = [
    "PDAflowInterop",
]
